### ISSUE TITLE
Unable to Sign in to VS Code from my azure account.

### ISSUE THREAD

**Issue by Himujjal** [microsoft/vscode-azure-account#146]
My process of signing in:
1. Install Azure Account extension in VS Code.
2. `Ctrl + Shift + P` and then `Azure: Sign in`
3. In status bar it shows: `Azure: Signing in...`
4. A new browser tab opens asking me to login to my Azure microsoft account. I do it.
5. Redirects to a page showing `You are signed in now and can close this page.`.
6. I go back to VS Code to check.
7. For more than 5 minutes it shows: `Azure: Signing in...`
8. I check in my Azure App Service extension. It still shows: `Waiting for Azure sign-in...`

In fact I have not been able to sign in at all. Come on man. All I had to do was to ease the deployment better. Azure is frustrating and I will switch to another platform soon. Please Help.

**Comment by tillik** [comment]
What do you have selected in your VS Code proxy settings exactly? 
Do you use Http: Proxy Support set to "override"?
If so, can you try switching to Http: Proxy Support "on" and what is the result then?

**Comment by kajwanr** [comment]
@Himujjal - I had a similar issue, however instead of showing "Waiting for Azure sign-in...", it just asked me to login again. 
In my case it was an issue with certificates which I solved by installing the [win-ca](https://marketplace.visualstudio.com/items?itemName=ukoloff.win-ca) add-on in VScode.

**Comment by chrmarti** [comment]
@Himujjal Could you check if there are any entries in the console (Help > Toggle Developer Tools)?

@kajwanr `win-ca` shouldn't be needed anymore with the latest versions of VS Code.

**Comment by kajwanr** [comment]
@chrmarti I am running 1.37 and but still had to use `win-ca`.

**Comment by chrmarti** [comment]
@kajwanr Which OS are you on?

**Comment by kajwanr** [comment]
@chrmarti 
Here is my info from Help->About: 
Version: 1.37.0 (user setup)
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T02:33:50.993Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.16299

**Comment by chrmarti** [comment]
Fixed the loading of certificates from the OS on Windows in https://github.com/microsoft/vscode/issues/79044.

Waiting for @Himujjal 's feedback on entries in the console when this happens (Help > Toggle Developer Tools).

**Comment by rfcm83** [comment]
I have the same problem. Visual Studio Code call browser, I login but callback is to 127.0.0.1:46/callback?code=...&session_state=46f1c5fa-0402-4d13-99ce-2c12d02616b7&state=…
![image](https://user-images.githubusercontent.com/7101449/63199420-20c98200-c07e-11e9-8821-d0d763837ebe.png)

**Comment by Himujjal** [comment]
@chrmarti I am able to sign in now.

I had a slow internet connection before. Like 20-30 KB/s due to working from a remote area and now I have a faster one. I took the same steps that I have mentioned.

But internet connection speed should be handled anyways.

**Comment by chrmarti** [comment]
Thanks @Himujjal, internet connection speed should indeed not have an effect. Let us know when you see this again.

@rfcm83 That looks similar to #129. What is the `state` query parameter set to on the first page of the sign-in in the browser and is the number there the same as the port at the end of the sign-in that fails?

**Comment by Lukas1v** [comment]
I have the same problem. I tried setting a proxy, but it did not work.

My help>about:
`Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:44.518Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-26-generic`

This was printed to my console:
`console.ts:137 [Extension Host] (node:3669877) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
b @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:409
_invokeHandler @ rpcProtocol.ts:394
_receiveRequest @ rpcProtocol.ts:310
_receiveOneMessage @ rpcProtocol.ts:237
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:623
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:623
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
I @ ipc.net.ts:32
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186`

**Comment by leshicodes** [comment]
Can we open this up? I've been having this issue for over year now.

**Comment by vaibhav-clearsense** [comment]
Having this issue since last week.

**Comment by alexweininger** [comment]
@leshicodes and @vaibhav-clearsense are you connected to a proxy server?

Proxies often cause issues with sign-in. See the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.

If that fix doesn't work for you, let me know. We can re-open this issue or open a new one.

**Comment by iammatthew2** [comment]
I'm currently having this problem on Mac OS with no proxies running

**Comment by NgCafai** [comment]
> What do you have selected in your VS Code proxy settings exactly? Do you use Http: Proxy Support set to "override"? If so, can you try switching to Http: Proxy Support "on" and what is the result then?

Hello ~ I have a similar problem when sign in to VS Code from github account, and I set the Http: Proxy Support to "off". It works!

**Comment by oviliz** [comment]
In my case I had to uninstall Azure Account and stick with the Azure Resources extension only.
Another Micro$oft mess...
