### ISSUE TITLE
where does vscode store azure account information after sign in

### ISSUE THREAD

**Issue by l6kuser** [microsoft/vscode-azure-account#150]
I have a vscode instance running in Windows and another instance running on Ubuntu/Linux.

Due to azure sign in restriction I can only sign in to Azure from within the vscode instance running on Windows. I can not do so from within the instance running on Ubuntu.

I would like to share the persisted account information after sign in from the Windows instance to the Ubuntu instance so that I can access Azure from the Ubuntu instance.

Where does vscode store azure account information after sign in?

**Comment by chrmarti** [comment]
We use the OS keychain (via the `keytar` NPM package).

Could you share why Ubuntu cannot sign in to Azure? (Is there something we can improve?)

**Comment by l6kuser** [comment]
The reason I can't sign in to Azure from Ubuntu has to do with the fact that I run Ubuntu as a virtualbox vm on my laptop and the vm/guest os is not regarded as a valid device from corp AD perspective. Only sign in from windows/host os on my laptop can pass the device check.

As most of my dev work is done on Ubuntu, I was hoping to find a way to share the persisted account info (e.g. access token) from host os to guest os.

**Comment by chrmarti** [comment]
On Windows you'll find it in the Credential Manager (named `VS Code Azure/Azure`). There might be a 'Show' button next to the password (on my machine there isn't, so that might depend on the version of Windows).

On Ubuntu check the keyring / passwords app.

On Ubuntu you might also want to try the alternate 'Device Code Sign-in' (`F1` > search for `Azure: Sign-in with Device Code`). It seems unlikely that this would work given the policy you mention, but it would be easier than copying tokens around.

**Comment by l6kuser** [comment]
The version of Windows I have doesn't have the show button. Even it has, it might just show the password (not the access token).

Also tried the device code sign-in on Ubuntu. The result is actually same as before so I still can't sign in.

We can close the ticket if there is no work around readily available.

**Comment by chrmarti** [comment]
Another approach might be to install VS Code on Windows and install the Remote-SSH (or Remote-Containers) extension to connect to the Ubuntu VM via SSH (if you can set up an SSH daemon there). But maybe that's going too far for what you need.

Closing thanks.
