### ISSUE TITLE
"Azure: Sign in" is not working if MFA is enabled

### ISSUE THREAD

**Issue by Andriy-dev** [microsoft/vscode-azure-account#177]
Azure: Sign in is not working if MFA is enabled on the account. 

Step to reproduce : 
1. Enable MFA on the account
2. Issue "Azure: Sign out"
3. Logout in the browser ( portal -> Sign Out )
4. Issue " Azure: Sign in" from VSCode
5. Login in Browser ( No MFA request )
6. Observe message "Visual Studio Code. You are signed in now and can close this page. "
7. VSCode still not logged in

Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**Comment by radikovo** [comment]
Still not working :( 

```
[error] Authentication failed.: Error: Authentication failed.
    at new t (c:\Users\alesr\.vscode\extensions\ms-vscode.azure-account-0.9.7\dist\extension.js:16:58871)
    at c:\Users\alesr\.vscode\extensions\ms-vscode.azure-account-0.9.7\dist\extension.js:16:49372
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by wwlorey** [comment]
@Andriy-dev, @radikovo are you still running into this problem with the latest version (0.9.8)?

**Comment by radikovo** [comment]
Now it works fine.

**Comment by Andriy-dev** [comment]
No more problem

**Comment by wwlorey** [comment]
Thanks for the update, please let us know if you run into any more problems

**Comment by yashvit** [comment]
I'm facing the same issue now. Not able to login into the vscode extension.

`Error: Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'xxxxxxxx'.\r\nTrace ID: xxxxxxxx\r\nCorrelation ID: xxxxxxxx\r\nTimestamp: 2022-12-16 06:48:59Z","error_codes":[50076],"timestamp":"2022-12-16 06:48:59Z","trace_id":"7ee0e96f-ef70-4576-b89f-2380400fc500","correlation_id":"xxxxxxxx","error_uri":"https://login.microsoftonline.com/error?code=50076","suberror":"basic_action"}`
