### ISSUE TITLE
Please help | azure application gateway doubt

### ISSUE THREAD

**Issue by Ashumishra14** [microsoft/vscode-azure-account#187]
Hi all,

I have created a application gateway but when  I am trying to access it via the public ip it thows error 502 to me.
On azure portal it shows me to set up the health probe of two webservers which I have added in the backend pool . when I tried to do that I am unable to determine the host and path to be given for the health probe. 
![502error](https://user-images.githubusercontent.com/65919526/83170326-fd198900-a131-11ea-8c53-fb31ca58aa29.PNG)
![health probe](https://user-images.githubusercontent.com/65919526/83170343-03a80080-a132-11ea-9211-19bb8efb96eb.PNG)

I have tried giving the webserver's dns name and also using 127.0.0.1 but no luck . 
please help me out as I am badly stuck at this point here specially in choosing the path and host .

**Comment by RMacfarlane** [comment]
Hi @Ashumishra14, this repository is meant to track issues with the Azure Account extension inside of VSCode. Since this is unrelated, I'm going to close it.

I don't personally know much about configuring application gateways on Azure, this documentation may be helpful: https://docs.microsoft.com/en-us/azure/application-gateway/overview You could also try asking your question on StackOverflow.
