### ISSUE TITLE
0.9.1 with support for new @azure packages only works with Insider version

### ISSUE THREAD

**Issue by caleteeter** [microsoft/vscode-azure-account#213]
I typically do dev with insider version of VS code and was surprised when I packaged my extension, and tested in retail version of VS Code that the dependency I have for the new @azure packages and v 0.9.1 of the azure account extension broke.  In the current retail version 1.47.3, version 0.8.11 of the azure account extension is installed.  I checked the extension package def for 0.9.1 and found that it require 1.48.0 or greater.  Is this something that will be available for retail VS Code soon?   Otherwise I have to revert to the old packages for azure integration (subscriptions, resource groups, etc.)

**Comment by caleteeter** [comment]
Also, I did download 0.9.1 and "tweaked" it by adjusting the vscode engine version to 1.47.3 and for the various azure package I use, it works fine.   Is this being held back for other package support?

**Comment by RMacfarlane** [comment]
This is intentional, we wanted to get some additional testing on the changes before its available in stable. We don't plan to decrease the engine version required for this extension, instead, please increase the required version for your extension. This does require users to keep up to date with VSCode to get new features, but this is something we want to encourage. 1.48.0 should ship this week.

**Comment by caleteeter** [comment]
Thanks @RMacfarlane , we will up the required version on ours!
