### ISSUE TITLE
Invalid redirect URI for Azure login in GitHub Codespaces.

### ISSUE THREAD

**Issue by pavinan** [microsoft/vscode-azure-account#306]
Azure login is not working in GitHub Codespaces.

It is creating redirect URL as https://myrepo.github.github.dev. (notice 2 githubs)
After having error page, I edited URL to single **github** and refreshed page. It worked.

![image](https://user-images.githubusercontent.com/8724933/131329792-e9c47678-6cce-41b5-9b95-6dd4320aee90.png)

**Comment by wwlorey** [comment]
Hi @pavinan, as an additional workaround for now - you can use the "Azure: Sign In with Device Code" command to sign in.

**Comment by wwlorey** [comment]
Closing this as I'm not able to repro the problem in Codespaces. My best guess is that it was fixed by the VS Code team. 

For more context: the local server's URL isn't something we control; it's assumed that the URL is localhost and Codespaces handles turning that into the appropriate github.dev URL.

Please let us know if you run into any more issues!
