### ISSUE TITLE
Fail to open the new issue page of Azure Account after clicking "Report an issue" button from notification

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azure-account#372]
**OS:** Windows 10
**VS Code Version:** 1.62.3
**Build Version:** 20211124.8
**Regression:** Not a regression

**Repro Steps:**
1. Install the Azure Account extension in VS Code -> F1 -> Azure: Sign In -> Click the "Back" button in the "Pick an account" page. (There is an error in the page.)
2. Navigate to VS Code, the error shows in the notification -> Click "Report an issue" button in the notification.
3. Check whether succeed to open the Azure Account new issue page.

**Expect:**
Succeed to open the new issue page of Azure Account .

**Actual:**
Fail to open the new issue page of Azure Account.
![azure](https://user-images.githubusercontent.com/45614674/143411135-52d2d880-69f3-4de6-b939-e8ddef29200a.gif)

**Comment by wwlorey** [comment]
I think the "access_denied" error after clicking "back" is fine. That's not an error we're throwing in the extension (it's being thrown by login.microsoftonline.com) and I don't think it's worth special casing it to show a different page.

But we should definitely fix the broken link when you click "report an issue". That's happening because of [this line](https://github.com/microsoft/vscode-azuretools/blob/8b547cd567c18d324bcaaa3d923105ce97f766f6/ui/src/reportAnIssue.ts#L85) in the UI package that uses the [extension's name from package.json](https://github.com/microsoft/vscode-azure-account/blob/ae01d6886a20886ca2aad5b24b703339aaf8172a/package.json#L2) to create the GitHub issue page URL. The problem is: the Account Extension's name is `azure-account` while the GitHub repo is named `vscode-azure-account` so it creates an invalid URL.
