### ISSUE TITLE
No notification appears after clicking "Sign Out and Reload Window" to take effect Authentication Library change and switch it again

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azure-account#378]
**OS:** Windows 10
**Build Version:** 20211130.7
**Regression:** Not a regression

**Repro Steps:**
1. Set the "Azure: Authentication Library" setting to "MSAL".
2. Click "Sign Out and Reload Window" button in the below notification.
![image](https://user-images.githubusercontent.com/45614674/144370802-a7090517-8adb-48ec-a80a-2621de355afa.png)
3. Switch the "Azure: Authentication Library" setting to "ADAL".
4. Check whether the notification "You must sign out and reload the window to..." appears or not.

**Expect:**
The notification "You must sign out and reload the window to..." appears.
![image](https://user-images.githubusercontent.com/45614674/144370940-4927378b-fecb-40dc-9892-84fa2dcea66e.png)

**Actual:**
No notification appears.

**More Info:**
The notification appears after executing "Sign Out"/"Select Subscription" command.
![123](https://user-images.githubusercontent.com/45614674/144372773-fd8123c2-ad6c-42d5-a9db-0daa81089276.gif)

**Comment by wwlorey** [comment]
The extension will listen to the `azure.authenticationLibrary` setting only after being activated. There's a few options we could take here:

1. Activate this extension with the [`onStartupFinished`](https://code.visualstudio.com/api/references/activation-events#onStartupFinished) activation event. After looking over the possible activation event options this seems to be the best, especially since VS Code settings can be changed via the JSON file or in the UI settings editor. But this would mean the extension activates even when it isn't needed.
2. Do nothing since the setting's description already directs people to sign out & reload:
    > The authentication library to use. The extension will choose a library for you if this setting is left blank. **Note: You must sign out and reload the window after modifying this setting for it to take effect.**

I'm leaning towards option 2 because I'm not a huge fan of always activating the extension. And the "you must sign out & reload" notification is meant to be a helpful nudge for people, not a hard requirement.

**Comment by wwlorey** [comment]
We decided to go with option 2.
