### ISSUE TITLE
[Remote Codespaces] The notification 'You must sign out and reload the window to authenticate with `"MSAL"`' pops up when switching the "Azure: Authentication Library" setting to default

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azure-account#390]
**OS:** Remote Codespaces
**Build Version:** 20211228.1
**Regression:** Not a regression

**Repro Steps:**

1. Set the "Azure: Authentication Library" setting to "MSAL" -> Sign in.
2. Set the "Azure: Authentication Library" setting to **default**.
3. Check whether the notification 'You must sign out and reload the window to authenticate with _`"ADAL"`_' pops up.

**Expect:**
The notification 'You must sign out and reload the window to authenticate with _`"ADAL"`_' pops up.
![image](https://user-images.githubusercontent.com/62053665/147654928-04b76925-5dea-4f9e-825d-0abe3cd16142.png)

**Actual:**
The notification 'You must sign out and reload the window to authenticate with _`"MSAL"`_' pops up.
![image](https://user-images.githubusercontent.com/62053665/147654961-3d3276cc-303f-4ab4-9053-6e87665ec444.png)

**Comment by wwlorey** [comment]
This is actually by design. We rely on the experimentation service to set the authentication library for us when the auth library setting value is an empty string. Here's that logic:

https://github.com/microsoft/vscode-azure-account/blob/4f0f32f65637a1ce81a067ac8b17d944db49dbb8/src/login/getAuthLibrary.ts#L22-L28

And the verbiage describing there auth library setting reflects this as well. From [package.json](https://github.com/microsoft/vscode-azure-account/blob/4f0f32f65637a1ce81a067ac8b17d944db49dbb8/package.json#L234):

> The extension will choose a library for you if this setting is left blank.
