### ISSUE TITLE
[Remote Codespaces] Pop up an error "The terminal process...failed to launch (exit code: 9)" when executing "Azure Cloud Shell (Bash)" 

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azure-account#391]
**OS:** Remote Codespaces
**Build Version:** 20211228.1
**Regression:** Not a regression

**Repro Steps:**

1. Set the "Azure: Authentication Library" setting to "MSAL" -> Make sure you are signed out of Azure.
2. Open VS Code's Terminal Pane -> Click the dropdown -> Select "Azure Cloud Shell (Bash)".
3. Check whether there is an error message "Cloud Shell does not currently support authenticating with MSAL..." in the terminal.

**Expect:**
There is an error message "Cloud Shell does not currently support authenticating with MSAL..." in the terminal, like below:
![image](https://user-images.githubusercontent.com/62053665/147740788-3d71fe69-f26b-4f7d-9d64-205983875a7e.png)

**Actual:**
Pop up an error "The terminal process...failed to launch (exit code: 9)", like below:
![image](https://user-images.githubusercontent.com/62053665/147740893-cb221eb0-3c34-49d4-b6b8-398290461d76.png)

**More Info:**
This issue also reproduces when the "Azure: Authentication Library" setting is "ADAL".

**Comment by dozer75** [comment]
I get the same error, but only when using Visual Studio Code against WSL and the Azure Account extension. Running Visual Studio Code and Azure Account extension without WSL works.

My reproduce steps are a bit simpler:
1. Install Azure Account extension
2. Log in using "Azure: Log in" command
3. Use the "Azure: Cloud Shell (Bash)" command

And I get the following error (the same way as above):
`The terminal process "/home/rg/.vscode-server/extensions/ms-vscode.azure-account-0.9.11/bin/node.sh '/home/rg/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/node', '-e', 'require('/home/rg/.vscode-server/extensions/ms-vscode.azure-account-0.9.11/dist/cloudConsoleLauncher').main()', '--ms-enable-electron-run-as-node'" failed to launch (exit code: 9).`

Running Visual Studio Code without WSL and it works as expected.

Environment:

Operating system: `Windows 11 Pro OS Build 22000.376`

WSL Distro: `Ubuntu 20.04.3 LTS`

Visual Studio Code:  `1.63.2 899d46d82c4c95423fb7e10e68eba52050e30ba3 x64`

Azure Account: `0.9.11`

A note: As you can see, I use the 0.9.11 extension while v-mengwe uses 0.9.12-alpha but the issue is the same. I have also tried older versions of the extension with the same result.

**Comment by v-xinda** [comment]
Verified on the build 20220204.15, this issue still reproduces on Linux OS.
