### ISSUE TITLE
Investigate supporting T2 credentials for ADAL

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azure-account#415]
Right now we only support T1 for ADAL and T2 for MSAL. But we don't want to force users to switch to MSAL for them to use the new T2 SDK.

**Comment by bwateratmsft** [comment]
In the one use case I found that Docker is using those credentials, we could use `getToken`. In fact that'd probably be easier.

Would fixing this issue be a prerequisite to unconditionally using `getToken` regardless of MSAL vs. ADAL?

**Comment by bwateratmsft** [comment]
(Bottom line is I'm trying to make sure the Docker extension doesn't get busted for this, regardless of Azure Account extension version, or ADAL vs. MSAL)

**Comment by nturinski** [comment]
> Would fixing this issue be a prerequisite to unconditionally using getToken regardless of MSAL vs. ADAL?

I think either way should be okay for Docker.  Though `signRequest` should definitely work since the credentials haven't changed since MSAL tokens appear to work for clients that require `signRequest`.  The issue we're running into is having an invalid access token when using ADAL with the new `WebsiteManagementClient`.  

I think if we implement `getToken` on the old credentials, it could be forward compatible.

**Comment by wwlorey** [comment]
Some thoughts @nturinski and I had after discussing offline: 

We should try getting rid of `DeviceTokenCredentials` for ADAL and replace it with our own class implementing `TokenCredential` and [`AzExtServiceClientCredentials`](https://github.com/microsoft/vscode-azuretools/blob/main/ui/index.d.ts#L147) (similar to how we created [`PublicClientCredential`](https://github.com/microsoft/vscode-azure-account/blob/30056757606d4fa73f38b9b521f14c34d7455b11/src/login/msal/PublicClientCredential.ts#L12)). We will need to verify these typings are compatible with type 1 and type 2 credentials.
