### ISSUE TITLE
[Suggestion] It would be better if keeping the cloud list consistent between the command palette and user setting

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azure-account#489]
**OS:** All
**Build Version:** 20220227.1
**Regression:** Not a regression

**Repro Steps:**

1. F1 -> Azure: Sign in to Azure Cloud -> Check the cloud list.
2. Open the setting -> Expand the dropdown list of the "Azure: Cloud" setting.
3. Check whether the cloud list is consistent between the step1 and step2.

**Actual:**
The cloud list is inconsistent between the step1 and step2.
![image](https://user-images.githubusercontent.com/57662131/155968580-901a57a6-6f2d-4d4c-9d3b-898814bea9d3.png)

**Suggestion:**
It would be better if keeping the cloud list consistent between the command palette and user setting.

**Comment by wwlorey** [comment]
`AzureCloud` is the new environment name that replaced `Azure`. At least according to this comment which predates my time with the extension:

https://github.com/microsoft/vscode-azure-account/blob/af40115544e7ef52c38d97df332a1b09122ac1a7/src/login/adal/AdalAuthProvider.ts#L150

I think it's fine to keep this around for backwards compatibility reasons. Especially since the `Azure: Sign In to Azure Cloud` entry point uses the latest naming for the default Azure environment:

https://github.com/microsoft/vscode-azure-account/blob/af40115544e7ef52c38d97df332a1b09122ac1a7/src/constants.ts#L41

**Comment by wwlorey** [comment]
After investigating this it appears that "Azure" and "AzureCloud" both work for signing in to default Azure

**Comment by v-xinda** [comment]
@wwlorey It would be better to remove one because "Azure" and "AzureCloud" both work for signing in to default Azure.

**Comment by wwlorey** [comment]
I'm hesitant about changing things in this extension unless the change is well understood and fully warranted. Authentication at Microsoft is a jungle and I don't know the implications of removing the (apparently?) old "Azure" option here. In other words, it ain't broke so let's not fix it.
