### ISSUE TITLE
Azure Account extention not working through proxy

### ISSUE THREAD

**Issue by munseym** [microsoft/vscode-azure-account#541]
Issue Type: <b>Bug</b>

Azure Account extention not able to work through the proxy.  http_proxy, https_proxy, HTTP_PROXY, HTTPS_PROXY all set. 
I originally had the same problem in the gitbash terminal when I tried "az login".  I was able to get it to work after "az account clear".  This does not appear to clear the credentials in the Azure Account extention.  I get back:
\n \n \n \n \n \n \n \n [\"http://www.boeing.com\"]\n \n \n \n \n \n \n Handshake failed.\n \n \n\n\n \n \n The SSL handshake could not be performed\n \n \n\n\n \n \n Host: login.microsoftonline.com\n \n \n \n \n Reason: Can't initialize server context:handshakefailed:server state 1:state 9:Application response 500 handshakefailed\n \n \n\n\n\n \n \n \n All Boeing Internet access is logged and may be monitored\n \n \n \n \n \n \n \n \n \n \n \n
This worked until I got a new computer.  It is possible that there is some cached credential that was restored to the new computer from backup.  It is not the one at ~/.azure , that one seems to correspond only to the terminal, not the extention.

Extension version: 0.10.1
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (15.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by munseym** [comment]
Is it possible that the extension is not honoring the REQUESTS_CA_BUNDLE environment variable?

**Comment by wwlorey** [comment]
@munseym please try signing out and back in using the "Azure: Sign Out" and "Azure: Sign In" commands which are accessible via the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette). Then try reinstalling VS Code if that doesn't work.

**Comment by munseym** [comment]
I have tried both of these and they did not resolve the problem.

**Comment by wwlorey** [comment]
@munseym have you configured VS Code to work with your proxy?

Here's a guide for that: https://code.visualstudio.com/docs/setup/network

**Comment by munseym** [comment]
Yes.  For example, after adding the environment variable REQUESTS_CA_BUNDLE I was able to use GItBash, ie "az login" inside VSC.  However, the Azure Account Extension specifically seems to be ignoring the environment variable.  I get the same error using the Azure Account Extension with REQUESTS_CA_BUNDLE as I get using "az login" _without_ REQUESTS_CA_BUNDLE.

**Comment by philliphoff** [comment]
@munseym Have you tried using the latest intermediate build ([0.10.2-alpha](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=47291&view=artifacts&pathAsName=false&type=publishedArtifacts))?  It has *a little* additional logging related to the URLs being accessed that may be helpful.

`REQUESTS_CA_BUNDLE` is an environment variable specific to Python, which is why it may work for the Azure CLI (being Python-based).  However, it's not a general HTTP proxy convention and so it wouldn't be expected to be honored by other platforms.  For example, Node.js has its own `NODE_CA_EXTRA_CERTS` environment variable.  However, VS Code being Chromium-based, doesn't honor that either.

Chromium-based applications (like VS Code) should be getting their certificate trust decisions from the system; I wonder if there's a necessary step to have your proxy certificate trusted by the OS itself that may not have been done yet on this new machine (or wasn't part of your machine restoration).

**Comment by philliphoff** [comment]
@munseym Another question, if you still have your prior machine, does the Azure Account extension still work on that machine?  Are there others in your organization using the Azure Account extension successfully?
