### ISSUE TITLE
Not allowing sign in when 2-factor authentication is enabled

### ISSUE THREAD

**Issue by AseerUZ** [microsoft/vscode-azure-account#646]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.loginToCloud
Error type: Error
Error Message: Get redacted:key returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'redacted:id'.\r\nTrace ID: redacted:id\r\nCorrelation ID: redacted:id\r\nTimestamp: redacted:id redacted:id05Z","error_codes":[redacted:id],"timestamp":"redacted:id redacted:id05Z","trace_id":"redacted:id","correlation_id":"redacted:id","error_uri":"redacted:url

Version: 0.11.1
OS: linux
OS Release: 5.13.0-52-generic
Product: Visual Studio Code
Product Version: 1.71.2
Language: en

<details>
<summary>Call Stack</summary>

```
Logger.createError extension.bundle.js:2:820371
extension.bundle.js:2:833256
```

</details>

**Comment by itimgit** [comment]
Same issue.

**Comment by alexweininger** [comment]
Could you add more detailed reproduction steps? At what point does the login process fail? And when does this error occur?

This error is often caused by the browser having an authenticated Azure session that needs to be refreshed (with MFA in this case). So you might be able to fix this by logging out in the portal in your browser, then signing back in (either in the portal or via the extension).
