### ISSUE TITLE
Extension is really slow to load in Windows User installation

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azure-account#87]
With the User install, it takes up to 2 min to load; on System install it takes about 10 seconds.

**Comment by chrmarti** [comment]
I can repro the 10 seconds (which is slow), but not the 2 minutes. Does it reliably reproduce? Could you create a cpu profile for that? (Reload with the Azure extensions hidden and then profile their startup.) https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions

**Comment by chrmarti** [comment]
This is all module loading time in the profile I'm looking at. One problem is that these are all synchronous file reads, so they can't run in parallel. Webpack should help some because it minimizes the number of files, but it will still be synchronous file reads.

@jrieken Have we thought about loading the extension modules asynchronously? Would Webpack allow that?

**Comment by jrieken** [comment]
> One problem is that these are all synchronous file reads, so they can't run in parallel

It is nodes & commonjs which is sync by definition... Not sure how to make things async because code often reads (and runs) like this `require('foo').callSomeFunc()`

**Comment by chrmarti** [comment]
New activation times (after the Webpacked release has been out for a week):
![image](https://user-images.githubusercontent.com/9205389/48568190-161b6a00-e8ff-11e8-80bc-1874edd87854.png)
