### ISSUE TITLE
Documentation on Proxy is not a solution

### ISSUE THREAD

**Issue by meiswjn** [microsoft/vscode-azure-account#906]
> Adding login.microsoftonline.com to your NO_PROXY environment variable will let requests to login.microsoftonline.com bypass the proxy. ([original suggestion](https://github.com/microsoft/vscode-azure-account/issues/676#issuecomment-1338281972))

From https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy

This is actually not really a solution. Especially in companies, it is not optional to use a proxy. In my case, it is not even technically possible to simply bypass the proxy.

This library should be compatible with proxies. It appears as if this library does not follow redirects (302), which might be the actual issue. Proxies are security tools that should not be bypassed and an official documentation should not advise users to do so.

As a workaround, we used "MSAL" instead of ADAL (default)

**Comment by alexweininger** [comment]
Hi @meiswjn, we've updated the Azure Resources extension so that the Azure Account extension is no longer used for authentication. It now uses VS Code's built-in Microsoft authentication extension which handles proxies a lot better than what the Azure Account extension could do. Many other users have stated it has fixed any proxy issues they had when using the Azure Account extension.

[Learn more about the new version of Azure Resources](https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.8.0)
