### ISSUE TITLE
Not able to sign in to Azure.

### ISSUE THREAD

**Issue by bhishma** [Microsoft/vscode-azure-account#92]
I get the following error when I try to sign in to Azure Account. I have added proxy settings as well.
My setup look slike this on Windows 7 Enterprise.

Version: 1.27.2 (system setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Error in Developer tools:
```
[Extension Host] Error: connect ETIMEDOUT 65.52.193.141:443
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:412
(anonymous) @ extensionHost.ts:224
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180

console.ts:136 
[Extension Host] Error: Acquiring user code failed
	at C:\Users\user1\.vscode\extensions\ms-vscode.azure-account-0.4.3\out\src\azure-account.js:550:28
	at Request._callback (C:\Users\user1\.vscode\extensions\ms-vscode.azure-account-0.4.3\node_modules\adal-node\lib\util.js:119:7)
	at self.callback (C:\Users\user1\.vscode\extensions\ms-vscode.azure-account-0.4.3\node_modules\request\request.js:186:22)
	at emitOne (events.js:116:13)
	at Request.emit (events.js:211:7)
	at Request.onRequestError (C:\Users\user1\.vscode\extensions\ms-vscode.azure-account-0.4.3\node_modules\request\request.js:878:8)
	at emitOne (events.js:116:13)
	at ClientRequest.emit (events.js:211:7)
	at TLSSocket.socketErrorListener (_http_client.js:387:9)
	at emitOne (events.js:116:13)
	at TLSSocket.emit (events.js:211:7)
	at emitErrorNT (internal/streams/destroy.js:64:8)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by bhishma** [comment]
Yes. I'm behind corporate proxy

**Comment by chrmarti** [comment]
Do you have the HTTP_PROXY and HTTPS_PROXY environment variables set?

**Comment by colinrippeyfinarne** [comment]
Hi @chrmarti can I ask for some help with getting vscode connected please?
(I find vscode's extension proxy related issues to be unbelievably frustrating).

I am behind a corporate firewall on a windows 7 laptop. The proxy config in IE is set to autodetect and there is a wpad server on the network. The wpad server itself has a wpad.dat file that returns a proxy or a DIRECT connection (depending on the hostnames being connected to, this is beyond my control).

VSCode will happily connect to check its own upgrade status etc. but there are some extensions (such as this one) which just don't seem to want to connect. 

I also have varying issues trying to get command line tools such as npm to connect out and so what I do is startup fiddler to act as the go between so that npm points to fiddler as its proxy, and fiddler then takes care of what upstream connection to make by examining the wpad.dat file.

This works for most things, fiddler will happily act as the go between for npm, git.

But...vscode extensions just don't seem to want to use fiddler. I get the same connectivity issue with the C# extension everytime there's an update it tries to download the omnisharp.zip package and fails...it cannot "see" the proxy and ends up getting a connection error (which it at least spits out an error message in the vscode terminal window)

So can you explain what it is we need to have in place for this specific vscode extension? You mention environment variables, and I assume you mean at the windows OS level, So I go into Computer Properties, Advanced, click Environment Variables and add in the HTTP_PROXY and HTTPS_PROXY values that point to http://localhost:8888 the default for fiddler. Is there any guide to this anywhere?

I have done this but I cannot see any traffic hitting fiddler from this extension.

I do the following:

1. Click the Sign in to Azure option
2. When the popup appears I click the Copy and Open option
3. I sign into Azure in the browser

But nothing then happens back in vscode. Eventually the Waiting for Azure sign-in just stops spinning and goes back to Sign in to Azure.

Is there any setting I can turn on to see if this extension is trying to make a connection? What is this extension doing, where in the code does it look for the environment variables? Have I perhaps configured some other underlying toolset such as NodeJS etc.

**Comment by chrmarti** [comment]
I should mentioned: I tested with the firewall denying all outgoing connections except to a single proxy server. I configured that with HTTP_PROXY and HTTPS_PROXY and sign-in worked. (That was on Linux, so there is still a chance of Windows showing different behavior, but there are no native modules involved, AFAIK.)

**Comment by chrmarti** [comment]
@colinrippeyfinarne Did you get it to work? Do you know what the URL of your PAC file is? I'm wondering if we could improve your case (which depends on how easy it is to get at the PAC file).
